### ISSUE TITLE
Remove entries in chinese

### ISSUE THREAD

**Issue by nukeop** [vitalets/github-trending-repos#116]
I noticed that chinese entries often pollute some of the more interesting categories, like this one:

https://github.com/vitalets/github-trending-repos/issues/28

When I sit to read them I notice that 3/4 are in chinese, therefore useless to most Github users. Could you filter them out?

**Comment by vitalets** [comment]
I think we should mirror original GitHub trends as is and not being opinionated.
Although I agree that not-translated Chinese repositories look disappointing.

I see two possible solutions:
* create simple [Tampermonkey](http://tampermonkey.net) script that will drop Chinese entries
* encourage Chinese developers to be part of world-community and translate popular projects in English

**Comment by unruledboy** [comment]
This is so biased! Take YouTube for example, it has many comments / posts in many different languages, will YouTube remove/block them? Of course not!

Just need to remember, none of us is the OWNER of this community, we are not totalitarianism here.

**Comment by jackalcooper** [comment]
Although generally I'm inclined to support the idea of using English on GitHub as much as possible, I think this is just a bunch of nonsense. Why would anyone need to worry about being "censored" or the "filter" when using any natural language of mankind on GitHub? What if there was a genius programmer speaks poor English and his or her project just couldn't get the notice it deserved under this kind of "purge" mechanism?

**Comment by nukeop** [comment]
This is an English-speaking website, the interface is in English, you're speaking English here, most of people interested in this project can't read Chinese, so it's useless to us. Many people expressed disappointment at this situation, not just me.

**Comment by rogerchina** [comment]
Yeah, it is good discussion, but I think, it is normal to use English in the international community, especially popular project, it should be open to world, not just China, actually,  many Chinese developers are good at English, however, they are lacking in international view probably, maybe never thought our work can affect you guys in the world.

**Comment by unruledboy** [comment]
@nukeop the thing is, developers are from all over the world, a lot of them simply don’t learn English well, if a project that is popular enough, it is the nature to have users internationally, and if they ask questions and give answers in there native languages, it would be natural, unless we say the project is for English users only, which forces the non-English speaking users to go away.

At the end of the day, it is the official website and go-to place.

And it should be individual’a choice to post/see the way he/she likes. A simple filter would suffice.

Wouldn’t you reckon so?

**Comment by nukeop** [comment]
I'm not saying they should be removed from Github altogether, but they should be filtered by the bot that posts daily/weekly trending repos in this project.

**Comment by nukeop** [comment]
If the algorithm pulls X top starred entries each day/week, entries in Chinese will pollute the pool and cause lower ranking entries in English to be skipped. Most developers around the world stick to English which became a de facto lingua franca in the programming world, so that their projects will be accessible and useful to the greatest possible number of people. Entries in Chinese are unusable for a majority of Github users, why can't these developers use English too?

**Comment by miao1007** [comment]
> Why so many Chinese like staring?

1. Many companies are recruiting a **Star Based** member, the more star, the more money. So they promote their project everywhere, even [buy stars](https://juejin.im/post/5b8c9310f265da4361530560) as 0.2$/star.
2. Most Chinese beginners can't identify the quality of the project, just star and star.
3. So a lot pool quality project are shown for all users.

> (you can) create simple Tampermonkey script that will drop Chinese entries for you personally

I've wrote a user script for **personal** drop down: <https://github.com/miao1007/github-trending-filter>, no self censorship, just modify the result as you like.
There are still many great project in Chinese, but most of them are both written in Chinese and English. It's believed that single-language project can be block safely.
