### ISSUE TITLE
Filter posts per language (Chinese)?

### ISSUE THREAD

**Issue by CameronBanga** [vitalets/github-trending-repos#120]
Signed up for three of these, and they're awesome. 

But getting a lot of Chinese repos in the emails (Java, Swift, and Obj-C). It's great that GitHub is so popular in China, but I don't read any Chinese, so these repos are useless to me.

Anyway there could be some sort of filtering per language for these?

**Comment by vitalets** [comment]
@CameronBanga 
I share the inconvenience. But just filtering out Chinese repos looks very opinionated to me. And for sure after some time we will get an issue "Why you filtering out Chinese entries?". 
I think we should find a better solution. Some already discussed in #116.
Also I can create separate issues with and without Chinese. But it will end with too many confusing issues.
I've asked support@github.com about filtering Chinese on trending page, let's wait the what they say.

Any more ideas?

**Comment by CameronBanga** [comment]
@vitalets That's a good point. Spent some time thinking about it, and you're right, there's not really a great solution given what is available.

Thanks for all your work though!

**Comment by unruledboy** [comment]
This is so biased! Take YouTube for example, it has many comments / posts in many different languages, will YouTube remove/block them? Of course not!

Just need to remember, none of us is the OWNER of this community, we are not totalitarianism here.

**Comment by vitalets** [comment]
I agree with you, @unruledboy !
I've contacted GitHub support and they promised to consider adding lang filter to trends.

**Comment by nukeop** [comment]
@unruledboy

Sure, we can't just ban all the Chinese, but this is a personal project so the owner can do as he pleases, and if he wished to do so, he could remove Chinese entries with no problems. Github has already been banned in Russia, so maybe China will follow suit soon.

**Comment by lgfinfo** [comment]
As a chinese,I agree with you, @unruledboy !

**Comment by nukeop** [comment]
Sadly this continues to be a problem, although this repo is a useful source of interesting news.

**Comment by vitalets** [comment]
I can add automatic translation via @matheuss [google-translate-api](https://github.com/matheuss/google-translate-api). The result can be like following:

[chaozh / awesome-blockchain-cn](https://github.com/chaozh/awesome-blockchain-cn)
收集所有区块链(BlockChain)技术开发相关资料，包括Fabric和Ethereum开发资料
> Collect all information related to BlockChain technology development, including information on Fabric and Ethereum development

***+122** stars today*

What do you think?

**Comment by Epistol** [comment]
Can't we just filter repos by language ? We can already almost do so by tech language (java, go, etc), why not by spoken language ? Also : is this repo still relevant due to Microsoft x Github situation ?

**Comment by vitalets** [comment]
> Can't we just filter repos by language ?

[GitHub trending page](https://github.com/trending) does not provide such filters.

> Also : is this repo still relevant due to Microsoft x Github situation ?

Yes, repo is relevant.

**Comment by Epistol** [comment]
Apparently Github trending page now support spoken language filter, basic with one choice for now but it's better than nothing.
