### ISSUE TITLE
Some threads aren't updated daily

### ISSUE THREAD

**Issue by nukeop** [vitalets/github-trending-repos#122]
Looks like e.g. Javascript and CSS aren't update daily anymore, were there no trending repositories on Github recently?

**Comment by vitalets** [comment]
Thanks for reporting. Just checked CircleCI status - they had some [issues on May, 8](https://status.circleci.com/). It seems to be a reason why job was not launched.
Currently the status reported as ok, but I still can't open my CI build page: https://circleci.com/gh/vitalets/github-trending-repos

@nukeop could you kindly check is above link working?

**Comment by nukeop** [comment]
Yeah it works. The most recent log shows 0 new repos for all categories.

**Comment by vitalets** [comment]
Now I see new repos [added to JavaScript](https://github.com/vitalets/github-trending-repos/issues/5#issuecomment-387910687)
As here trending repos are cached in issue comments (for a month) it is possible that some languages can have no new repos. Although GitHub shows something. This is done to avoid posting the same repos every day. Especially for less popular languages where trends can hang for a long time.

But it never occurred with JavaScript / CSS. So let's see for some time.

**Comment by vitalets** [comment]
Closing as everything works ok for several months.
