### ISSUE TITLE
Remove the non-relevant Chinese repo in trending repo

### ISSUE THREAD

**Issue by Edwardchengar** [vitalets/github-trending-repos#137]
Recently half of trending repo are wrote by Chinese and no English version. Sometime the project even not relevant to any tech, they just share news/info for Chinese. E.g. 996.ICU,zju-icicles
It is quite difficult for us to find out the interesting project when I browse the trending repo. I knew there was some issue discussed this problem before. however the problem seems become more and more serious...

**Comment by vitalets** [comment]
Hi! I think currently we have the best option. All non-english entries are automatically translated into english:
![image](https://user-images.githubusercontent.com/1473072/55963369-5d721080-5c7b-11e9-96d8-34cc3a72e67c.png)

Previously discussed here: https://github.com/vitalets/github-trending-repos/issues/116
