### ISSUE TITLE
No longer receiving notifications for Fortran

### ISSUE THREAD

**Issue by dmey** [vitalets/github-trending-repos#142]
It has been a few weeks since I last received notifications from Fortran weekly (https://github.com/vitalets/github-trending-repos/issues/127). I tried to unsubscribe and subscribe again last week but nothing changed -- has something changed at your end?

**Comment by vitalets** [comment]
Thanks for reporting! 
Fixed - here are a [comment](https://github.com/vitalets/github-trending-repos/issues/127#issuecomment-586145332) with new trending Fortran repo.

Although there can be weeks without notifications if there is no **new** trending repos in Fortran (they are cached in comments for 30 days).
