### ISSUE TITLE
Please add SQL

### ISSUE THREAD

**Issue by pniewiadowski** [vitalets/github-trending-repos#146]
{https://github.com/trending}  
- [ https://github.com/trending/sql?since=daily] daily
- [https://github.com/trending/sql?since=weekly ] weekly

**Comment by vitalets** [comment]
Although `sql` is supported on trending page, there are no repos neither daily nor weekly.
![image](https://user-images.githubusercontent.com/1473072/92229905-dbf3d180-eeb2-11ea-802f-aa1a353a2259.png)
