### ISSUE TITLE
Please add PLSQL

### ISSUE THREAD

**Issue by pniewiadowski** [vitalets/github-trending-repos#147]
{https://github.com/trending}  
- [ https://github.com/trending/plsql?since=daily ] daily
- [ https://github.com/trending/plsql?since=weekly ] weekly

**Comment by vitalets** [comment]
Although `plsql` is supported on trending page, there are no repos neither daily nor weekly.
![image](https://user-images.githubusercontent.com/1473072/92230032-16f60500-eeb3-11ea-86b2-6af4f042555d.png)
