### ISSUE TITLE
Strip mentions from repo descriptions

### ISSUE THREAD

**Issue by fgaz** [vitalets/github-trending-repos#170]
It's subscribing me to issues and spamming my notifications

**Comment by vitalets** [comment]
> It's subscribing me to issues and spamming my notifications

Ok. Could you show link to issue?

**Comment by fgaz** [comment]
https://github.com/vitalets/github-trending-repos/issues?q=is%3Aissue+fgaz

**Comment by vitalets** [comment]
Fixed. In future comments mentions should be stripped.

**Comment by fgaz** [comment]
Thanks
