### ISSUE TITLE
How often the script should run?

### ISSUE THREAD

**Issue by vitalets** [vitalets/github-trending-repos#42]
I'm getting different feedback about notifications frequency and would like hear what do you think:

* From one side running script every hour ensures that you will be notified about all trending repos  and no repo will be missed. But it potentially can cause several notifications within a day.
* From the other side running it less often may be not enough to catch all trending repos. Some interesting repo can appear and disappear as the competition there is strong. GitHub updates both [trending today](https://github.com/trending?since=daily) and [trending this week](https://github.com/trending?since=weekly) several times a day.

**Comment by sneas** [comment]
I've just had to unsubscribe from `trending weekly` issue because it gives too many notifications (i received several in few hours). Expected it to be notified once a week.

**Comment by vitalets** [comment]
I've updated the schedule - now daily check runs **once a day** and weekly check runs **every friday**.
