### ISSUE TITLE
Support LaTeX

### ISSUE THREAD

**Issue by natestemen** [vitalets/github-trending-repos#58]

**Comment by vitalets** [comment]
It seems GitHub does not show exactly LaTeX on trending page. 
What about binding to TeX: https://github.com/trending/tex ?

**Comment by natestemen** [comment]
yeah that would be great!

**Comment by vitalets** [comment]
Missed the update. Added!
* https://github.com/vitalets/github-trending-repos/issues/177
* https://github.com/vitalets/github-trending-repos/issues/178
