### ISSUE TITLE
Please add trending repos for the nix language

### ISSUE THREAD

**Issue by makefu** [vitalets/github-trending-repos#62]
https://github.com/search?utf8=%E2%9C%93&q=language%3ANix&type=Repositories&ref=advsearch&l=Nix&l=

that would be fantastic!

**Comment by vitalets** [comment]
Done in #96 (daily), #97 (weekly).
The first comment will contain all currently trending repos, and all following comments will contain only updates.

**Comment by makefu** [comment]
Awesome, thanks!

**Comment by vitalets** [comment]
You are welcome! Thanks for suggestion.
